name: Fetch RSS Feed
on:
  schedule:
    # During "Central European Time" (CET): Offset from UTC: -1
    - cron: '30  8,9,10,11,12,13,14,15  *  11-12,1-3 1-5'
    # During "Central European Summer Time" (CEST): Offset from UTC: -2
    - cron: '30  7,8,9,10,11,12,13,14   *  4-10      1-5'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch RSS
        run: |
          npm run fetch

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rss/*
          git diff --cached --exit-code || git commit -m "Update RSS feed"
          git push
